# A small docker-compose for local development.
#
# There are no custom-built images here. Instead we use Docker volumes to point
# generic images at the right resources needed to spin up everything using local
# builds. To do this, create a `.env` file with the following settings:
#
# - TTPEDIA_MY_OS: any basic Docker image that can run your debug Rust binaries
# - TTPEDIA_DATA_PREFIX: an absolute path where the persistent data volumes will go
#   Recommended to put them in `./local/data/`.
# - TTPEDIA_FAKTORY_PASSWORD: a password for Faktory authentication
#
# The frontend will be exposed on http://localhost:29080/, the backend web API on
# http://localhost:29180, the backend WebSockets API on ws://localhost:29180/. The
# Faktory web UI is exported on its default port 7420.

services:
  faktory:
    image: contribsys/faktory:1.9.3
    volumes:
      - faktory_data:/var/lib/faktory:rw
    ports:
      - "7420:7420"
    environment:
      FAKTORY_PASSWORD: ${TTPEDIA_FAKTORY_PASSWORD}
    command:  /faktory -b :7419 -w :7420 -e production
    healthcheck:
      test: [ "CMD", "wget", "-q", "http://:${TTPEDIA_FAKTORY_PASSWORD}@localhost:7420/" ]
      start_interval: 5s
      start_period: 60s
      interval: 90s
      timeout: 2s
      retries: 3

  compiler_worker:
    image: ${TTPEDIA_MY_OS}
    volumes:
      - ./backend/target/debug/ttpedia_compilerworker:/ttpedia_compilerworker:ro
    environment:
      FAKTORY_URL: "tcp://:${TTPEDIA_FAKTORY_PASSWORD}@faktory:7419"
    command: /ttpedia_compilerworker
    depends_on:
      faktory:
        condition: service_healthy

  repo_server:
    image: ${TTPEDIA_MY_OS}
    volumes:
      - ./backend/target/debug/ttpedia_reposerver:/ttpedia_reposerver:ro
      - repo_data:/repodata:rw
    environment:
      FAKTORY_URL: "tcp://:${TTPEDIA_FAKTORY_PASSWORD}@faktory:7419"
      TTPEDIA_REPO_ALLOWED_ORIGIN: http://localhost:29080
    command: /ttpedia_reposerver /repodata
    depends_on:
      faktory:
        condition: service_healthy

  backend_facade:
    image: nginx:1.29
    volumes:
      - ./local/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "29180:80"
    depends_on:
      - repo_server

  frontend:
    image: node:24
    volumes:
      - ./frontend:/app:rw
    ports:
      - "29080:3000"
    environment:
      # NB, these are what the *client* communicates with, so they're "outside
      # Docker" URLs, not "inside Docker":
      NUXT_PUBLIC_BACKEND_API_BASE: http://localhost:29180/ttpapi1
      NUXT_PUBLIC_REPO_WEBSOCKETS_URL: ws://localhost:29180/ttpapi1/repo/sync
    command: |
      bash -c "cd /app && yarn dev"
    depends_on:
      - backend_facade

volumes:
  faktory_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: ${TTPEDIA_DATA_PREFIX}/faktory_data
  repo_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: ${TTPEDIA_DATA_PREFIX}/repo_data
