[package]
name = "ttpedia-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
axum = { version = "0.8.4", features = ["ws"] }
automerge = "0.6.1"
clap = { version = "4.5.42", features = ["derive"] }
console-subscriber = "0.4"
futures = "0.3.31"
openat = "0.1"
samod-core = { path = "../../samod/samod-core" }
samod = { path = "../../samod/samod", features = [
    "axum",
    "tokio",
    "tungstenite",
] }
serde = { version = "1", features = ["derive"] }
serde-automerge = { path = "../../serde-automerge" }
#thiserror = "2"
tokio = { version = "1.47.1", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
    "tracing",
] }
tokio-tungstenite = { version = "0.27.0", features = ["native-tls"] }
toml = "^0.9"
tracing-subscriber = "0.3.19"
